<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $general_image
 * @property integer $company_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $news_categories_id
 *
 * @property NewsCategories $newsCategories
 */
class News extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['created_at', 'updated_at', 'news_categories_id', 'company_id'], 'integer'],
            [['news_categories_id'], 'required'],
            [['title'], 'string', 'max' => 200],
            [['news_categories_id'], 'exist', 'skipOnError' => true, 'targetClass' => NewsCategories::className(), 'targetAttribute' => ['news_categories_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'company_id' => 'Company Id',
            'general_image' => 'General Image',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'news_categories_id' => 'News Categories ID',
        ];
    }

    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }

    public function afterSave($insert, $changedAttributes)
    {
        //parent::afterSave($insert, $changedAttributes);
        Yii::$app->locator->cache->set('id', $this->id);
        // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNewsCategories()
    {
        return $this->hasOne(NewsCategories::className(), ['id' => 'news_categories_id']);
    }

}
